server:
  port: 80
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  devtools:
    remote:
      secret: 123
  datasource:
    url: jdbc:mysql://localhost:3306/vet-docker-test
    username: developer
    password: Schultz81449487
  jpa:
    properties:
      hibernate:
        show_sql: 'true'
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  server:
    error:
      whitelabel:
        enabled: 'false'